version: "3"
services:
  app3:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: web_app3
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    expose:
      - "80"
    volumes:
      - ./htdocs:/var/www
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./apache2.conf:/etc/apache2/apache2.conf
    networks:
      - webdocker-network

# Docker Networks
networks:
  webdocker-network:
    external:
      name: dockerweb_webdocker-network
